version: '2'
services:
  sampleapplication-app:
    image: sampleapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sampleapplication-mssql:1433;database=SampleApplication
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 9090:9090
  sampleapplication-mssql:
    extends:
      file: mssql.yml
      service: sampleapplication-mssql
